Issue 196: Fix multiple additions of images to DOM
hlxsites/caesars pull request #209
Opened 2023-04-24 17:32 UTC by tmathern

Fix https://github.com/hlxsites/caesars/issues/196

## 🔗 Test URLs:
  
- Before: https://main--caesars--hlxsites.hlx.page/caesars-palace/
- After: https://issue-196--caesars--hlxsites.hlx.page/caesars-palace/

## 📝 Description:
  
Repro: The issue can be reproduced by changing window size with the pointer. On size change switch mobile/desktop, images will be added to the DOM/

2023-04-25 05:59 UTC, amol-anand commented
This is brutal as you already mentioned 😄 
Hold off on merging this. It should not be this complicated. Is this because they want a totally different image in mobile or that the ootb sizing is not sufficient? you can also use getOptimizedPicture() and pass in the right width for each breakpoint etc.. 
And this has gotten to a point where it no longer should be in the default/ootb columns block. Might be better off as a separate block instead.

2023-04-25 06:00 UTC, amol-anand requested changes
Hold off on merging this. It should not be this complicated. Is this because they want a totally different image in mobile or that the ootb sizing is not sufficient? you can also use getOptimizedPicture() and pass in the right width for each breakpoint etc..

2023-04-25 17:13 UTC, tmathern commented on caesars-palace/blocks/columns/columns.js
> -        image.closest('picture').replaceWith(createOptimizedPicture(image.src, image.alt, false, [{ width: '768' }]));
Why did we need this here explictly again?

2023-04-25 22:23 UTC, tmathern commented on caesars-palace/blocks/columns/columns.js
> -        image.closest('picture').replaceWith(createOptimizedPicture(image.src, image.alt, false, [{ width: '768' }]));
The bug occurs only if using "replaceWith". I suspect it has to do something with the fact that replaeWith will do some cloning (hence we'll loose the original `picture` reference we got through the closure). I tried putting an id on the picture to grab it by id and move it, but a duplicate still managed to appear. So if we don't need all this, it's probably best to drop it.

2023-04-26 16:48 UTC, swetabar approved these changes
LGTM!

2023-04-26 16:56 UTC, merged